spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: olzzhas
    password: Olzhas040404
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true